# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    docker:
      # Specify the Ruby version you desire here
      - image: circleci/ruby:2.5.1-node-browsers

    steps:
      - checkout
      - restore-cache:
          keys:
            - aamva-api-client-gem-bundle-{{ checksum "Gemfile.lock" }}
      - run:
          name: Install dependencies
          command: |
            bundle check || bundle install --retry=3 --path vendor/bundle
      - save-cache:
          key: aamva-api-client-gem-bundle-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: Run Tests
          command: |
            bundle exec rspec spec/lib
