#!/bin/bash
set -euo pipefail

PFX_PATH="${1:-}"
PASSWORD_PATH="${2:-}"

if [[ -z $PFX_PATH || -z $PASSWORD_PATH ]]; then
  echo "Usage: $0 [pfx path] [password path]"
  exit 1
fi

PASSWORD=$(cat $PASSWORD_PATH)

# See https://stackoverflow.com/a/9516936
openssl pkcs12 -in "$PFX_PATH" -passin "pass:${PASSWORD}" -nocerts -out aamva-private-key.pem -passout "pass:${PASSWORD}"
openssl pkcs12 -in "$PFX_PATH" -passin "pass:${PASSWORD}" -clcerts -nokeys -out aamva-public-key.pem
